sigp/discv5

Cargo.toml
README.md
src/config.rs
src/discv5.rs
src/discv5/query_info.rs
src/discv5/test.rs
src/kbucket.rs
src/lib.rs
src/packet/auth_header.rs
src/packet/mod.rs
src/query_pool.rs
src/query_pool/peers/predicate.rs
src/rpc.rs
src/service.rs
src/session/crypto.rs
src/session/mod.rs
src/session_service.rs
src/session_service/timed_requests.rs
src/session_service/timed_sessions.rs
src/transport.rs

This updates the case where a future can be dropped when attempting to send a packet over the UDP socket. The major changes are:
- Remove async-std dependency and used tokio udp socket
- Use `poll_send_to()` for sending packets
- Updates documentation
- Version bump

Correct sending async future

---

src/session_service.rs
src/session_service/timed_sessions.rs

It is possible that multiple timeouts can be created. This leads to the possibility of not having a session or request exist in the timeout mapping when the delay_queue returns the object.
This PR prevents this from happening by updating a timeout if it exists rather than creating a new one.
This also downgrades an error warning.

Handle timeout error

---

src/discv5.rs
src/lib.rs
src/session_service.rs

This improves the Session management of peers.
Peers that do not respond to requests have their sessions dropped. 
Sessions that get created via returned messages have their timeouts extended.

Improved Session handling

---

src/discv5.rs
src/kbucket.rs
src/kbucket/bucket.rs

Allows the application to manually remove nodes from the routing table

Enable manual removal of nodes from routing table

---

src/config.rs
src/discv5.rs

Allows a configuration to be set which prevents nodes from entering the local routing table. 
It can be set using the `Discv5ConfigBuilder` as follows:
```rust
// prevent all nodes with a non tcp6 port from entering the routing table
let config = Discv5ConfigBuilder::new().table_filter(|enr| enr.tcp6().is_some()).build();
```
This has not been tested on a large network and is only introduced for developers experimenting with discv5

Implement a table-filter configuration

---

Cargo.toml
src/handler/mod.rs
src/handler/tests.rs
src/service.rs

It was previously possible to fill a channel between the service and the handler whilst the handler simultaneously filled the channel to the service. 
This scenario results in a deadlock as either service is awaiting the other to consume messages from the queue. 
This PR updates the service sending channel to be unbounded which frees it from waiting for the handler and allows it to freely consume handler requests at its leisure. 
The handler will still block if excessive messages are received from the network and await the service to complete its processing.

Remove channel locking

---

Cargo.toml
examples/find_nodes.rs
src/config.rs
src/handler/mod.rs

This updates the crate to alpha.7
This contains the following updates:
- A bug-fix (The Jonny Prevention Patch) which removes an active_request_auth mapping for requests that get responded to.
- Updates to dependencies to accommodate the ed25519 update
- Increase in the default size of the session cache, to prevent sessions expiring early and rapidly.

Alpha.7 update

---

Cargo.toml

Adds the `openssl-vendored` feature so that we can choose to statically link the openssl library. This will be nice for portable builds and dependency-minimization for Lighthouse.
Some other public crates that depend on openssl also do this (e.g., [here in reqwest](https://github.com/seanmonstar/reqwest/blob/dd8441fd23dae6ffb79b4cea2862e5bca0c59743/Cargo.toml#L34)).

Add feature to vendor openssl

---

src/service.rs
src/service/test.rs

Since updating to unbounded channels a number of async functions were left that no longer need to be async. 
This PR removes them.

Remove unnecessary async functions

---

src/handler/mod.rs
src/handler/tests.rs

added logic for caching hash(local-node-id) and test for src_id method. this was done to avoid hash calc that happens when a client is repeatedly sent `RandomPackets` 👀
resolves #32
@AgeManning lmk if i need to change anything or if you want more context

cache hash(local_node_id)

---

src/handler/mod.rs
src/handler/session.rs
src/packet/mod.rs

Uses the number of messages sent per session as the first 32 bits of the Nonce used to encrypt packets. 
The remaining 64 bits are randomly generated. This ensures nonce's are not replayed per session, unless more than 2^32 messages are sent per session. Sessions expire in the order of days, making this limit virtually impossible to hit.

Message counter for AES-GCM Nonce

---

src/handler/mod.rs

In the function [handle_challenge](https://github.com/sigp/discv5/blob/839254cfb8fc3cd6bb3176393839793e31f0303d/src/handler/mod.rs#L512), both of the variables (enr, node_address) points to the same instance of NodeContact:
- enr comes from [the request_call.contact](https://github.com/sigp/discv5/blob/839254cfb8fc3cd6bb3176393839793e31f0303d/src/handler/mod.rs#L601)
- node_address comes from [the request_call.contact](https://github.com/sigp/discv5/blob/839254cfb8fc3cd6bb3176393839793e31f0303d/src/handler/mod.rs#L543-L546)
So I think that [the verification](https://github.com/sigp/discv5/blob/839254cfb8fc3cd6bb3176393839793e31f0303d/src/handler/mod.rs#L604) can be omitted. 💡

Remove unnecessary verification

---

src/service.rs

Peers with unknown ENR's are being temporarily added into the DHT. 
This PR prevents non-contactable ENR's from etnering the DHT initially. This prevents unnecessary PING requests to non-contactable ENRs. 
This also adds error logging to failed RPC requests.

Prevent NAT peers entering DHT

---

Cargo.lock
Cargo.toml
src/lib.rs

Adds default `log` events for discv5 for backwards compatibility and log users.

Add logging by default

---

src/error.rs
src/handler/mod.rs
src/handler/session.rs
src/packet/mod.rs

If a signature is invalid for a specific handshake challenge, we maintain the challenge and allow the correct signature to be requested again

Maintain session challenge

---

src/discv5.rs

Adds a public method to mark a node as `Disconnected` in the dht.

Add a `disconnect_node` public method

---

src/query_pool/peers/closest.rs
src/rpc.rs
src/service.rs

Attempt to avoid the loop described in https://github.com/sigp/lighthouse/issues/2215
The rationale for this change (credits to @pawanjay176) is that [`Enr::udp_socket`](https://docs.rs/enr/0.5.0/src/enr/lib.rs.html#369-376) only returns IPv4 addresses, whilst `IpVote::majority` can return IPv6 addresses. Therefore, when the majority address is an IPv6 address it will never be the case that `Some(majority_socket) != local_socket` and node will consistently attempt to update its address but never consider it successfully updated.
This PR explicitly ignores ipv6 addresses since it is my understanding that the rest of this code base is not ipv6-ready.
Note: I had to run `cargo fmt --all` to appease CI. You'll notice a couple of additional changes in the diff.

Add mitigation for ipv6 loop

---

src/rpc.rs

If a peer sends a ping response with an ipv6 address that is ipv4 compatible/mapped, then auto-convert to ipv4.
Related to https://github.com/sigp/discv5/pull/62

Auto-coerce to ping response to ipv4 when possible

---

src/kbucket.rs
src/kbucket/bucket.rs
src/service.rs

This provides a number of corrections associated with the previous feature update.
Specifically, 
- Correctly handling of inserting pending peers into the routing table
- Adds initial ENRs into the untrusted list to account for cases when peers get removed from the routing table during a query.

Feature update patches

---

src/handler/mod.rs

This is an optimisation that prevents sending WhoAreYouRef requests to the service every time a packet has unknown session keys. 
A WhoAreYouRef is only requested from the service if we are not already waiting for a response. 
Further, this corrects the lrucache such that multiple unknown requests from a node does not restart the WHOAREYOU request timeout.

Whoareyou timeout

---

src/handler/mod.rs
src/service.rs

There are lots of logs for responses that come in late after a query has ended.
This PR downgrades the log to `debug` level to avoid spamming the user.

Downgrade warning log

---

src/kbucket/bucket.rs
src/kbucket/key.rs

This PR fixes an issue in `KBucket::update_value` that caused two nodes to be removed rather than one when the filter check failed. It also updates the value of `first_connected_pos` so that it remains consistent in the case of a removal.
Testing has been expanded through a new `quickcheck` test which updates a value in the presence of a filter. I've also re-jigged some of the other quickcheck infra to make use of an `Arbitrary`-aware generator for `NodeId`, and refactored some of the common checks into `KBucket::check_invariants`.

Fix issues in `update_value`

---

src/service.rs

This just adds a getter for node_address: NodeAddress in Impl TalkRequest.
This is useful if you want to send a talk request to a node that sent you one. Because you can find their ENR from it.

Add getter function for node_address

---

src/kbucket/bucket.rs

Modify `KBucket::remove` so that it updates `first_connected_pos` and can no longer be used to violate the internal invariants of the bucket, i.e. ensure that `first_connected_pos` remains correct & in bounds.
I've also added a new quickcheck test that applies random actions from `KBucket`'s public interface in a random order. This should provide us with some reassurance that regardless of how `KBucket`'s methods are used by the rest of the crate, it will never panic. 
The only mutable methods from `KBucket` that are excluded from the new test are `pending_mut` and `get_mut`. The reason for their omission is that they're unrelated to the removal bug, and are limited in the damage they can do (they can't _remove_ bucket entries).

Update first connected pos in `KBucket::remove`

---

src/service.rs

Added warn log to notice users that no known_closest_peers found. And I think it's better to return empty result immediately in the case.

Emit warn log when no known_closest_peers found

---

src/discv5.rs
src/service.rs

- Removed mut self from find_enr()
So I am making this PR because to my knowledge the mut self isn't required and it will work without mutability. I am not the most knowledgeable in Rust, but it does seem to be unnecessary correct me if I am wrong.
It would be nice to have this not mutable because then you can use it from an Arc reference of the Discv5 Impl.
@AgeManning

Remove mut self from find_enr()

---

Cargo.toml
src/handler/mod.rs
src/lib.rs
src/lru_time_cache.rs

close https://github.com/sigp/discv5/issues/71
- use `hashlink::LinkedHashMap` as it's better to avoid to write unsafe code
- I have measured performance of LruTimeCache with the benchmark code below. LruTimeCache was `1,142 ns/iter`, while std::collections::HashMap was `664 ns/iter`.
- It is good score
- for your reference, I run [this benchmark]( https://github.com/maidsafe/lru_time_cache/issues/143#issue-756136904), lru_cache_sum was `101,426 ns/iter`
> test lru_time_cache::bench::hashmap_sum        ... bench:         664 ns/iter (+/- 195)
> test lru_time_cache::bench::lru_time_cache_sum ... bench:       1,142 ns/iter (+/- 187)
```rust
mod bench {
extern crate test;
use test::Bencher;
use std::cell::RefCell;
use std::collections::HashMap;
const RANGE: usize = 32 * 1024;
const …
```

Re-implement lru-time-cache

---

src/discv5.rs
src/kbucket.rs
src/service.rs

Modify `nodes_by_distances` method of `KBucketsTable` to take a slice argument for `log2_distances`.
I'm not sure whether we need to bump the version given it's marked as beta. Also, AFAIK we (trin) are the only consumers of the recently public `kbuckets` module API.

Modify nodes_by_distances to take slice arg instead of Vec

---

src/discv5.rs
src/discv5/test.rs

We're using `Discv5` in trin, in a multithreaded (async) context. I find it somewhat painful to have to lock the `Discv5` instance to use most of the APIs.
My read is that, internally, `Discv5` already locks the internal values to make for safe multi-threaded usage. I think we can make that apparent/accessible in the API by just converting the `&mut self` to `&self` everywhere possible (basically everywhere except for startup and shutdown, both of which are not a problem for us).
I'm curious what you folks think about this approach, or if you have suggestions for how trin could use a `Discv5` instance across threads without locking it at every invocation.

Allowing multithreaded Discv5 calls, without locking

---

src/discv5.rs
src/kbucket.rs

In [Trin](https://github.com/ethereum/trin), we are manually managing the overlay instance of the routing table (`KBucketsTable<TNodeId, TVal: Eq>`) and the buckets (`Vec<KBucket<TNodeId, TVal>>`). For example, we are using a custom bucket refresh lookup algorithm which is first picking buckets with index 239-255, then we select a target bucket and generate a random NodeID falling in the target bucket range. (For more details please check this PR: https://github.com/ethereum/trin/pull/213)
To make this possible, we need public access to the `buckets`  field in `KBucketsTable` and a way to check if a random NodeIi falls in a target bucket index (mainly for testing purposes).
Please advise what would be the most convenient way to accomplish this, happy to tweak this PR to meet maintainers' …

Public kbuckets access and bucket index

---

src/discv5/test.rs
src/service.rs
src/service/query_info.rs

Queries that contain a target attempt to contact the target to search for itself.
Previously this resulted in an RPC error as highlighted in #108. 
This PR permits these RPC requests and adds the target in the found closest peers, if that peer is contactable.

Gracefully handle queries that contain the target

---

src/handler/mod.rs
src/handler/session.rs
src/lru_time_cache.rs

Attempt to handle issues raised by @ackintosh here: https://github.com/ackintosh/test-plan-discv5/pull/13#issuecomment-1120430861
From what I can tell it seems we attempt new handshakes even when one is underway. 
To address this, I think we can prevent sending messages if we are awaiting a challenge response. We wait for either the response, or a timeout before sending the message and optionally establishing a new session. 
This way, it should work the first go, and we don't have to increment the number of retries.
@ackintosh - Could you check to see if this PR resolves your issue. (Sorry for the delay, have a few things going on).

Correct Handshake race condition

---

examples/find_nodes.rs
src/discv5.rs
src/handler/mod.rs
src/handler/tests.rs
src/node_info.rs
src/service.rs

Closes #96.
Add a new `Discv5Event` variant to surface ENRs from established sessions (completed handshakes). This change essentially propagates the `HandlerOut::Established` event upward so that the application layer can receive the event. The propagated ENR does not go through the "contactable" check performed in `inject_session_established`. Therefore, the application has no guarantee that the ENR from this event is contactable.
The discussion in the associated issue suggested this path to resolution. If `SessionEstablished` does not represent desired semantics, then please suggest a more appropriate name.

Add Discv5Event::SessionEstablished to surface ENRs

---

README.md

This adds a brief outline for our design decision to drop requests from implementations that advertise non-contactable addresses in their ENR.
This issue continually comes up, so I think its necessary we add it to our README.

ENRs for Discv5

---

src/service.rs

Make `Discv5Event::SocketUpdated` happen only when updating local ENR has been succeeded.

Small improvement for the `Discv5Event::SocketUpdated` event

---

src/discv5.rs

There are two double-lock bugs in `update_local_enr_socket`.
`local_enr` is RwLock.
The first read lock:
https://github.com/sigp/discv5/blob/878ef13378017bd8e5bf6426f23c3bf02f9e427d/src/discv5.rs#L353
The second write locks:
1. https://github.com/sigp/discv5/blob/878ef13378017bd8e5bf6426f23c3bf02f9e427d/src/discv5.rs#L371-L373
2. https://github.com/sigp/discv5/blob/878ef13378017bd8e5bf6426f23c3bf02f9e427d/src/discv5.rs#L376-L378
The fix is to replace the first read lock with one write lock,
and reuse the write lock.

Fix a double-lock bug in update_local_enr_socket

---

src/kbucket.rs

If the `local_key` is provided for `ClosestBucketsIter` start it start in `Start(BucketIndex(0))` instead of `Done`. otherwise, the `closest_*` iterators will always be empty and make it impossible lookup the local node in the DHT.
this is also the state libp2p-kad starts with if the local key was provided.
https://github.com/libp2p/rust-libp2p/blob/e530118fb017122786180570b2b68f89aac53905/protocols/kad/src/kbucket.rs#L361-L365
See also: https://docs.rs/libp2p-kad/0.41.0/src/libp2p_kad/behaviour.rs.html#831-856

fix: start with bucket idx 0 if local key

---

src/kbucket.rs
src/rpc.rs
src/service.rs

I don't see the purpose of this limit. If anything, I think it might hurt communications with other discovery implementations. It will ignore requests with more than 10 distances. The spec doesn't seem to have any limits on the number of distances in the request message, just the recommendation that the result is limited to 16 nodes, which is already done:
https://github.com/sigp/discv5/blob/878ef13378017bd8e5bf6426f23c3bf02f9e427d/src/service.rs#L996-L999
The `nodes_by_distance` function will stop adding to the results when the limit (`self.config.max_nodes_response`) is reached. By default, this configuration value is 16, [like the spec recommends](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#findnode-request-0x03). And the maximum packet size of 1280 should …

Remove FINDNODE request bucket limit

---

src/service.rs

When reviewing the nodes response handler, I noticed that the maximum number of responses check is a bit weird. It will print a warning if there are going to be more than 15 packets (`DISTANCES_TO_REQUEST_PER_PEER * 5`) but it will stop processing after 6 (`self.config.max_nodes_response / 3 + 1`) packets. Am I understanding this correctly?
This PR will:
* Make a new constant: `MAX_RESPONSES`
* Use this constant for both checks.

Update max responses check for nodes response

---

src/handler/active_requests.rs
src/handler/mod.rs
src/handler/request_call.rs
src/handler/tests.rs

Moves the request call struct into its own file to reduce excess logic in the handler

Move RequestCall into individual file

---

src/handler/active_requests.rs
src/handler/mod.rs
src/handler/request_call.rs
src/handler/tests.rs

right now the handler does requests on itself to get the ENR of a multiaddr session. This makes it so that if this request fails/timeouts we don't report those failures to the service.
Notes:
- This will be needed to handle nat hole punching handler requests correctly
- Right now, the FINDNODE request for a multiaddr session can both fail and timeout without affecting the session itself. So it seems to be that the only purpose of requesting and obtaining the enr is adding a peer to our kbuckets on a `HandlerOut::Established` event. Not sure if this is intended but seemed notable to me.

Separate handler requests from service requests

---

Cargo.toml

I think it will be nice if `discv5` imports the `enr` crate with the `serde` feature, This allows Serialization/Deserialization of the `discv5::Enr` type out of the box.

Update `enr` crate version and add `serde` feature

---

.github/workflows/build.yml
README.md
examples/request_enr.rs
src/lib.rs

The flag `--tests` limits the `cargo test` to the tests, leaving behind the doctests, and it seems to be the examples as well.
This removes this flag to expand ci and fixes the failing checks

ci: expand and fix checks

---

src/discv5.rs

The API prevented users from updating the TCP port in the ENR to match the current UDP socket. 
This corrects the logic and allows users to update the tcp port if needed.

Update tcp socket correctly

---

src/discv5.rs
src/service.rs

I made a pr which adds ``send_ping`` to discv5.rs the reason for this is I am implementing the missing calls for Trin's discv5 rpc and in order to implement ``discv5_ping`` I need to expose it from this library first.

Expose ``send_ping`` from service.rs for discv5.rs

---

Cargo.toml
examples/find_nodes.rs
src/discv5.rs
src/discv5/test.rs
src/handler/crypto/ecdh.rs
src/handler/crypto/mod.rs
src/node_info.rs

This updates to the latest version of ENR. 
This change updates the underlying crypto libraries as well as some encoding improvements. 
This does create a breaking API change also. 
This resolves #171

Update to ENR v0.8.1

---

src/discv5.rs
src/service.rs

This PR is related to my last one in terms of me implementing things Trin needs for its rpc here is my issue tracking it https://github.com/ethereum/trin/issues/689
So it looks like request_enrs does kind of what we want but the main difference is we want to be able to set the distance for ourself and have the ability to get more then just one ENR back.
I am open to feedback if you guys would prefer we refactor FindEnr but keep request_enr the same in discv5 just add distance set it to vec![0], then move the verification code to check if there is only 1 enr to after the channel? I am not sure if that would be ideal just throwing a quick idea out there, if what I have isn't what you guys think is ideal for this.

Implemented find_node_designated_peer to call a designated peer with distance

---

README.md
src/lib.rs
src/rpc.rs
src/service.rs

[(https://github.com/sigp/discv5/pull/183)](https://github.com/sigp/discv5/pull/183) was prematurely merged into master branch when the intention was to merge it to the discv5.2 topic branch, my bad.

Remove topics

---

src/config.rs
src/executor.rs
src/ipmode.rs

Fixed some new clippy lints raised after updating to Rust 1.70.
The errors that were happened are here:
```
error: this is an outer doc comment and does not apply to the parent module or crate
--> src/config.rs:5:1
|
5 | ///! A set of configuration parameters to tune the discovery protocol.
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_doc_comments
= note: `-D clippy::suspicious-doc-comments` implied by `-D warnings`
help: use an inner doc comment to document the parent module or crate
|
5 | //! A set of configuration parameters to tune the discovery protocol.
|
error: this is an outer doc comment and does not apply to the parent module or crate
--> …
```

Appease clippy in Rust 1.70

---

src/handler/mod.rs
src/service.rs

Downgraded an error log which would occur quite frequently for ipv6 only nodes in an ipv4-dominated network. 
I also increased a log which was hiding messages being dropped because of invalid source addresses.

Improve logs for ipv6 support

---

src/handler/mod.rs
src/service.rs
src/service/test.rs

A connection direction can unexpectedly change from Outgoing to Incoming in the scenario shown in [this diagram](https://github.com/sigp/discv5/pull/184#issuecomment-1562032339). The diagram shows a specific case in PING/PONG. However, if we generalize this, when an `Outgoing` connection is established and the other node returns WHOAREYOU, the ConnectionDirection will change to `Incoming` at the time the new session is established. This could potentially cause some problems. e.g. IpVote doesn't work as IpVote ignores Incoming connections.
This PR makes the service to set only initial connection direction and not update it if a node already exists in the routing table.
I have tested this PR with the PING/PONG simulation (https://github.com/sigp/discv5/pull/184), and confirmed that the …

Fix unexpected ConnectionDirection update

---

src/config.rs
src/handler/mod.rs
src/handler/session.rs
src/handler/tests.rs

Our discv5 implementation drops a request if the source IP address doesn't match the ENR. For PING request, due to this behaviour, the source node can't notice that its external IP address has been changed.
Here is a simulation that reproduce that issue. 
https://github.com/ackintosh/discv5-testground/pull/98
This PR makes discv5 to respond PING even if the source IP address doesn't match.
I introduced **one-time session** at handler to encrypt PONG response without storing a (normal) session. One-time session here is a session for a specific request such that a PING request mentioned above. As the name implies, one-time session is removed once it's used.
Added config parameters for one-time session introduced by this PR.
- one_time_session_timeout
- one_time_session_cache_capacity
These …

Respond to a PING even if the source doesn't match the ENR

---

Cargo.toml

This bumps the ENR version and resolves #201 
I think this can be minor version bump. Primarily bug fixes in this release. What do you think @divagant-martian ?

Version bump to v0.3.1

---

src/lib.rs

- Docs were using explicit references instead of relying on cargo finding them. This leads to broken links that `rustdoc` does not catch (because it trusts us), main one was the `Session`, which is private.
- Reword some descriptions to point to concrete modules and structs.
- Remove any mention to advertisement since it was removed.
- Remove some attributes that have not been necessary for a long time
From reading the docs, tempted to remove the `Discv5` prefix as it was done in `rust-libp2p`. Would look cleaner internally and it seems unnecessary externally

fix entry docs

---

README.md
examples/custom_executor.rs
examples/find_nodes.rs
examples/request_enr.rs
examples/simple_server.rs
src/config.rs
src/discv5.rs
src/discv5/test.rs
src/error.rs
src/handler/crypto/mod.rs
src/handler/mod.rs
src/handler/session.rs
src/handler/tests.rs
src/lib.rs
src/query_pool/peers/closest.rs
src/query_pool/peers/predicate.rs
src/service.rs
src/service/test.rs

Removes the `Discv5` prefix from various types. Within the crate it's obvious the event emitted by `Discv5` belongs to `Discv5`, making `Discv5Event` overly verbose. Crate users are encouraged to use as `discv5::Event` instead of `Discv5Event` and similar
also removed some advertisement docs that were missed in a prev pr

refactor for removing `Discv5` prefix

---

src/rpc.rs

addresses #207 
verify that received data does not contain extra bytes when doing rlp encoding.
This is (I think) appropriate workaround to what I would consider either a bug or an api shortcoming in `rlp`

fix rpc decoding to reject extra data

---

src/handler/mod.rs
src/handler/tests.rs

```mermaid
sequenceDiagram
participant Node1
participant Node2
Node1 ->> Node2: Random packet
Note over Node2: send_challenge()<br> expected_response: 1
Node2 -->> Node1: WHOAREYOU
Node1 ->> Node2: Handshake Message(FINDNODE)
Node2 -->> Node1: NODES
rect rgb(100, 0, 0)
Note over Node2: expected_response remains 1
end
```
I've enhanced `multiple_messages` test: 
- replaced `Handler::spawn()` with `build_handler()` and `Handler::start()`
- added assertions to test handler's states

expected_responses remains after challenge has been completed

---

src/discv5.rs

Closes #211.
- Add a method to `Discv5`, `external_enr`, which returns an `Arc<RwLock<Enr>>`

Expose underlying ENR representation externally

---

src/handler/mod.rs
src/handler/tests.rs
src/ipmode.rs
src/rpc.rs
src/service.rs
src/service/test.rs

This PR closes https://github.com/sigp/discv5/issues/217.
In this PR, if we received a PONG response with zero port number, the following logs will be output, and the response will be ignored.
```
2023-10-19T22:22:23.827733Z DEBUG discv5::rpc: The port number should be non zero: 0
2023-10-19T22:22:23.827762Z  WARN discv5::handler: Failed to decode message. Error: Custom("PONG response port number invalid"), Node: 0xb862..63b1, addr: 16.0.0.3:9000
```

Changing port of ReponseBody::Pong to NonZeroU16

---

src/handler/mod.rs
src/service.rs

Adjust some common logs seen on https://github.com/sigp/lighthouse/pull/4979
- Query time out; Queries always have a callback, so this error is always informed in the form of an event, the caller can decide what to do with this
- Failed FINDNODE; unclear what kind of errors are happening. I suspect we will be downgrading this log eventually
- Blacklisting peer. Log was not very descriptive of what is actually going on
- IP mode info. Before we would only know this on start, not on creation. Since this is no longer the case the two logs (start and creation) can be merged

Adjust some logs

---

Cargo.toml

we don't use `tracing-subscriber` in discv5. Having this as a dependency potentially created a duplicated dep that is not even used
na

make tracing-subscriber a dev dep

---

Cargo.toml
src/lru_time_cache.rs

- Include proptest v1.1.0 in cargo.toml dev dependencies
- Draft proptest in lru_time_cache that tries to panic tagging of key values
- Need to implement checking of keys in cache expiring
- Code needs significant factoring and optimisation
- Prints for debug need to be removed

Draft proptest for tagging of keys in lru_time_cache

---

Cargo.toml
src/handler/request_call.rs
src/kbucket/entry.rs

This PR fixes some warnings in master and bumps the libp2p version. 
This also bumps the discv5 crate to 4.1

Fix warnings and bump libp2p

---

src/discv5.rs
src/handler/request_call.rs
src/kbucket.rs
src/kbucket/entry.rs

allows optimistic and less blocking interaction with discv5

Allow optimistic mirror of kbuckets with read lock only

---

Cargo.toml
README.md
examples/custom_executor.rs
examples/find_nodes.rs
examples/request_enr.rs
examples/simple_server.rs
src/config.rs
src/discv5.rs
src/discv5/test.rs
src/error.rs
src/handler/active_requests.rs
src/handler/crypto/mod.rs
src/handler/mod.rs
src/handler/nat.rs
src/handler/session.rs
src/handler/tests.rs
src/ipmode.rs
src/lib.rs
src/node_info.rs
src/query_pool/peers/closest.rs
src/query_pool/peers/predicate.rs
src/rpc.rs
src/rpc/response.rs
src/service.rs
src/service/test.rs
src/socket/filter/mod.rs

Merge lastest `master` branch into `discv5.2`.
I have updated the `Config::session_cache_capacity` type from usize to NonZeroUsize in 6d4fce2f05f51823021f971be41d4de379c313ad, for the following reasons:
- `Config::session_cache_capacity` is utilized in [Handler's session](https://github.com/ackintosh/discv5/blob/6d4fce2f05f51823021f971be41d4de379c313ad/src/handler/mod.rs#L332) (LruTimeCache) and in [`Nat::new_peer_latest_relay_cache`](https://github.com/ackintosh/discv5/blob/238dbc0d6d390f249157ce32027431577059efb9/src/handler/nat.rs#L59) (LruCache).
- The type of `Nat::new_peer_latest_relay_cache` is LruCache and the argument for `LruCache::new` is NonZeroUsize

Merge `master` into `discv5.2`

---

src/service.rs

Fixes buggy log message. Log message was comparing the length of the list of requested distances with the list of received nodes. This pr instead prints the distance requested.

Fix buggy log message

---

src/lru_time_cache.rs

optimize LruTimeCache::remove_expired_values by only iterating once

optimize LruTimeCache::remove_expired_values

---

Cargo.toml

A new patch version of ENR was released fixing a few bugs. 
This PR updates discv5 to tag the latest minor version so users get access to the patches.

Pin ENR to the latest minor

---

examples/find_nodes.rs
src/discv5.rs

Removes unused events.
Piggy-backing on https://github.com/sigp/discv5/pull/250 which introduces breaking changes.

Remove unused event `EnrAdded`

---

Cargo.toml
src/discv5.rs
src/lib.rs
src/node_info.rs

Replaces `libp2p` with `libp2p-identity` and `multiaddr` which significantly lowers the amount of dependencies pulled in by the crate. Closes #253 
This PR also re-exports those two crates as they are needed to use some of the features introduced by the `libp2p` feature, so users end up adding the dependency in their tree manually on top. Closes #254 
Both changes are in their own commits, so I can split it off into two PRs if needed

chore: slim deps

---

src/socket/filter/cache.rs
src/socket/filter/mod.rs

This PR fixes the clippy errors: https://github.com/sigp/discv5/actions/runs/9783383578/job/27016940537?pr=258
I removed `ReceivedPacket` because it no longer has the `content` field (as it was unused) and now only has the `received` field.
- [] ~~Documentation updates if relevant~~

Fix clippy errors

---

examples/find_nodes.rs
src/handler/mod.rs
src/handler/session.rs
src/rpc.rs
src/service.rs
src/socket/filter/mod.rs
src/socket/recv.rs
src/socket/send.rs

Changes logging statements from using string formatting to structured logging. Closes #222 
- ~~[ ] Documentation updates if relevant~~

Move to structured logging

---

src/lib.rs
src/service.rs

Fixes the clippy errors encountered in https://github.com/sigp/discv5/actions/runs/10463483509/job/29002624738?pr=261

chore: fix clippy errors

---

Cargo.toml
src/handler/crypto/mod.rs
src/packet/mod.rs

This PR updates aes-gcm and is related to #260

chore!: Update aes-gcm to 0.10.3 and aes to 0.8.4

---

.github/workflows/build.yml

This PR gets rid of the warning displayed in actions:
https://github.com/sigp/discv5/actions/runs/10463483509?pr=261
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3.

Bump up actions/checkout version to v4

---

README.md
src/handler/mod.rs
src/handler/session.rs
src/handler/tests.rs
src/service.rs

It can be the case that peers have invalid ENRs (i.e report socket addresses that do not match the socket src of the packet). 
Previously discovery would drop packets from these peers and log a warning. This PR shifts this logic to instead respond to the src socket but exclude the ENR from reaching our routing table. 
We will not advertise these peers, but we will respond to them. 
I think this change will improve overall connectivity.
There are some legitimate cases where an ENR can be invalid, such as the external IP address changing or some funky NATs.

Respond to requests from peers with invalid ENRs

---

src/service.rs
src/service/test.rs

On IPv4 dominated networks, local routing tables can be fully populated with ipv4 nodes limiting the number of ipv6 ping/pong responses. This can prevent the enr-auto-update from finding and updating a node's ENR to its external socket. 
For security reasons, we can't just accept PONG responses from any node on the network. For this reason, we only ping peers that make it into our routing table as a number of security measures must be passed for a node to enter the table. However if the table is full, we reject peers from entering and therefore do not attempt to PING them. 
This PR suggests the following mechanism:
If a peer fails to make it into the routing table, and we are lacking votes on either IPv4 or IPv6 and this peer can add a vote AND they are an outgoing peer (i.e one that we …

More lenient ipv6 auto-update

---

src/handler/mod.rs

Downgrades a common log which no longer has significant impact as we now respond to these peers

Downgrade invalid session logs

---

src/config.rs

I have been looking into complications with low ipv6 peers in real world networks. 
Originally this default was set, to handle ip changes more rapidly, however with low ipv6 peers on networks this becomes a hindering factor. 
Although it is configurable, the default should be large enough to accommodate real-world networks. 
I think this might have been originally set when we ping'd every connection. As no longer do that, maintaining pong votes for 2 minutes seems to be a reasonable tradeoff.

Increase default vote duration to 2 minutes

---

Cargo.toml
src/config.rs
src/metrics.rs
src/service.rs
src/service/connectivity_state.rs
src/service/test.rs

Symmetric NATs and IPv6 are currently a pain point in discovery. Discv5 has a mechanism to discover its external IP and port (`socket` from now on). We use a majority voting system based on `PONG` responses. 
The problem is that full-cone NATs can be included in the IP address discovery. Furthermore, with ipv6, all connections are likely not NAT'd and the external IP discovery is going to return our IPv6 address. 
Currently we are assuming that if our external address is discoverable, that we are contactable (as we get discovered when a correct port forward is established in ipv4). However this will generally not be the case for full-cone NATs and IPv6. In fact, if we default to dual-stack, all ipv6 nodes will update their ENR to their ipv6 address, rendering them non-contactable (as ipv6 …

Automatic Firewall/NAT Detection

---

Cargo.toml

Updates the crate to version 0.9.0 ahead of a release.

Version bump  v0.9.0

---

src/kbucket/bucket.rs
src/rpc.rs

Well updating from the old rlp library to the new one alloy_rlp there was a regression for encoding/decoding TalkRequests, which is required for the Portal Network.
I noticed something was broken when trying to upgrade Trin to alloy back in Apr 5, 2024. I delayed upgrading https://github.com/ethereum/trin/pull/1231 because I didn't have time to debug this issue at the time.
So here is the fix to the regression and a few tests to prevent it from happening again

Fix encode TalkRequest regression during library transition

---

Cargo.toml
src/kbucket/bucket.rs
src/service.rs
src/service/ip_vote.rs

I've been testing Ipv6 and dual stack support. 
There was a bug, where in dual-stack mode, if a router has not SNAT'd correctly they use random source ports. The `majority()` voting system will never reach a majority and we will continue to ping all peers we see. 
We waste a lot of traffic as we are never going to reach a majority in this scenario. The correct logic is not to check for a majority on a specific port before asking more more PING's rather, if we have enough PONG responses to reach a majority if our NAT was correctly set up, then no longer send more PINGs. 
This PR updates to this new logic.

Prevent dual-stack spamming

---

src/discv5.rs

```rust
pub fn try_from_enr(enr: Enr, ip_mode: IpMode) -> Result<Self, NonContactable> {
let socket_addr = match ip_mode.get_contactable_addr(&enr) {
Some(socket_addr) => socket_addr,
None => return Err(NonContactable { enr }),
};
Ok(NodeContact {
public_key: enr.public_key(),
socket_addr,
enr: Some(enr),
})
}
```
Every time we were sending a talk request we were converting the `Enr` to `NodeContact`. In doing this operation we call `public_key()` or in other terms we are recovering the public key every time we send a talk request, in Portal we send all our messages over TalkRequests, currently `public_key()` is taking over 8.7% of the samples I get from running my benchmark https://github.com/ethereum/trin/pull/1660, by reusing the NodeContact we can avoid repetitively recovering the …

perf: use NodeContact instead of Enr for sending talk_req()

---

src/node_info.rs

I want to be able to construct the NodeContact object myself. As I want to impl From<X> for NodeContact {} in our codebase, since for us Enr will always be present so having it behind a option is inconvenient 
@jxs @AgeManning @ackintosh ping for review

Add constructor for NodeContact

---

src/node_info.rs

Every time we send a talk_request `node_address()` is called which calls `node_id()`
```
pub fn node_id(&self) -> NodeId {
self.public_key.clone().into()
}
```
Hence every time we send a TalkRequest we are deriving the node_id from `self.public_key.clone().into()`  the signature which is very computationally expensive, especially as we are sending metric tons of talk requests
If the Enr is already present we don't need to re-derive the node_id so if it is present just use the node_id already derived
@AgeManning @jxs @ackintosh ping for review

perf: don't derive node_id from signature unless required

---

src/service.rs

The PING mechanism for discv5 informs our peers of ENR updates as the sequence number is included with the PING. We ping every connected peer by default every 5 minutes (not all at once, each peer has a 5 minute timer). 
Once we have decided that our ENR should be updated (given the PONG's from our peers have aligned on a fixed value) we have been sending out PINGs to all our peers to inform them to update our ENR. This is an optimization that allows us to quickly form connections and get our ENR into the routing table of other peers as soon as we know we are externally contactable. 
We are investigating an issue, whereby a non-stable decision as to our external address can lead to ping amplifications. If we think this is likely to happen, it probably isn't worth this optimization, also …

Remove ping optimization
