Cargo.toml
examples/find_nodes.rs
src/discv5/test.rs
src/session_service/tests.rs

Replaces poll_fn and futures::select+timeout combo with `tokio::select!`.

Upgrade async code

---

Cargo.toml
examples/find_nodes.rs
src/discv5.rs
src/discv5/test.rs
src/lib.rs

Adds a user-facing query-id, such that users can match results to specific queries.

Add a user-facing query id

---

Cargo.toml

Updates deps to latest versions, this includes a security fix in ENR which can cause panics when decoding malicious strings as ENRs. 
This includes a crate version bump

Package updates

---

src/discv5.rs
src/executor.rs
src/handler/hashmap_delay.rs
src/handler/mod.rs
src/handler/tests.rs
src/kbucket/key.rs
src/metrics.rs
src/node_info.rs
src/packet/mod.rs
src/service.rs
src/service/query_info.rs
src/socket/filter/cache.rs
src/socket/mod.rs

Adds clippy lints to the latest update

Apply clippy lints

---

.github/workflows/build.yml
src/discv5.rs
src/discv5/test.rs
src/error.rs
src/lib.rs
src/service.rs
src/socket/recv.rs
src/socket/send.rs

This PR is the result of integrating the new discv5 format into lighthouse. 
It adds a number of bug fixes, stability in thread management and modified API. 
Of particular note is the creation of static futures for the public API. This allows collection of these API's in non-async context to be polled independently of the `discv5` underlying struct.

Stability upgrades and added API features

---

.github/workflows/build.yml
Cargo.toml
src/handler/mod.rs
src/lib.rs
src/node_info.rs

Improve github workflows and correct feature build

Improve github workflows

---

src/discv5.rs
src/discv5/test.rs
src/kbucket.rs
src/service.rs
src/service/test.rs

Closes #16 
Make old service tests work with the new discv5 structure.

Fix service tests

---

README.md
examples/custom_executor.rs
examples/find_nodes.rs
examples/request_enr.rs
examples/simple_server.rs
src/discv5.rs
src/discv5/test.rs
src/error.rs
src/handler/mod.rs
src/handler/tests.rs
src/service.rs
src/service/test.rs
src/socket/filter/mod.rs
src/socket/mod.rs

Propagates UDP socket binding errors to the user

Propagate UDP socket binding errors to the user

---

Cargo.toml
examples/find_nodes.rs
src/error.rs
src/handler/crypto/mod.rs

This removes openssl and uses rust-crypto in its place.

Remove openssl dependency in favour of rust-crypto

---

Cargo.toml

Bump version to v0.1.0-alpha.10

Version 0.1.0.alpha-10

---

src/handler/mod.rs
src/handler/tests.rs

Tiny fixes

---

Cargo.toml
src/socket/mod.rs

Update net2 to socket2

---

src/service/query_info.rs

Fix doc comment

---

src/error.rs
src/packet/mod.rs
src/service.rs
src/socket/mod.rs
src/socket/recv.rs
src/socket/send.rs

Drop a packet with invalid packet size

---

Cargo.toml
examples/find_nodes.rs
src/discv5.rs
src/discv5/test.rs
src/handler/crypto/ecdh.rs
src/handler/crypto/mod.rs
src/node_info.rs
src/rpc.rs
src/service.rs

Updates the dependencies of discv5, in particular:
- ENR
- RLP
The updates contain crypto modifications due to the underlying cryptography library updates

Dependency update

---

.github/workflows/build.yml
src/config.rs
src/discv5.rs
src/handler/mod.rs
src/kbucket.rs
src/kbucket/bucket.rs
src/lib.rs
src/query_pool/peers.rs
src/socket/filter/cache.rs
src/socket/filter/config.rs

- Adds the ban duration to the configuration builder
- Re-orders some of the configuration options
- Adds a new github action to check doc links

Improve ConfigBuilder

---

src/handler/crypto/mod.rs
src/handler/hashmap_delay.rs
src/handler/mod.rs
src/handler/session.rs
src/kbucket.rs
src/kbucket/entry.rs
src/packet/mod.rs
src/query_pool.rs
src/query_pool/peers/predicate.rs
src/service.rs
src/service/hashset_delay.rs

Remove some unnecessary borrows

Update for Clippy 1.54.0

---

Cargo.toml
src/handler/crypto/mod.rs
src/handler/hashmap_delay.rs
src/handler/mod.rs
src/handler/session.rs
src/kbucket.rs
src/kbucket/entry.rs
src/packet/mod.rs
src/query_pool.rs
src/query_pool/peers/predicate.rs
src/service.rs
src/service/hashset_delay.rs

Building upon https://github.com/sigp/discv5/pull/80, cut a beta.9 release

Version 0.1.0-beta.9

---

src/discv5.rs
src/kbucket/bucket.rs
src/kbucket/entry.rs
src/service.rs

Improves error handling in kbuckets and removes unnecessary mutability in kbucket modifications.

Improve error handling and mutability

---

src/metrics.rs
src/socket/filter/mod.rs
src/socket/recv.rs
src/socket/send.rs

Removes some obsolete and memory-consuming metrics and adds bandwidth usage metrics.

Add bandwidth metrics

---

examples/find_nodes.rs
src/config.rs
src/handler/mod.rs
src/lib.rs
src/packet/mod.rs
src/permit_ban.rs
src/query_pool/peers/closest.rs
src/service.rs

Fixing some small lints and example errors for the latest rust.

Clippy lints and code improvements

---

Cargo.toml

This version includes a number of dependency updates that resolve cargo audit issues.

Version 0.1.0-beta.13

---

Cargo.toml
src/handler/active_requests.rs
src/handler/mod.rs

https://github.com/sigp/discv5/issues/42
Fix security vulnerabilities of merged PR https://github.com/sigp/discv5/pull/101 
Nothing to add

Active requests fixup

---

Cargo.toml

Upgrades the libp2p-core dependency

Upgrade libp2p-core dep

---

Cargo.toml

to address the changes of #112

Bump discv5 version

---

.github/workflows/build.yml
Cargo.toml
src/handler/crypto/ecdh.rs
src/handler/crypto/mod.rs
src/kbucket/key.rs
src/service/query_info.rs

this was triggered by trying to update to ENR v0.6.2. All the changes done are required simply by trying to update this dep

Version upgrades

---

Cargo.toml

Version bump to v0.1.0

---

examples/custom_executor.rs
examples/simple_server.rs
src/discv5.rs
src/discv5/test.rs
src/handler/mod.rs
src/handler/session.rs
src/ipmode.rs
src/kbucket.rs
src/kbucket/bucket.rs
src/packet/mod.rs
src/service.rs
src/service/ip_vote.rs
src/service/test.rs
src/socket/mod.rs
src/socket/recv.rs

Fixing some things that IntelliJ pointed out:
* Replace `assert!(a == b)` with `assert_eq!(a, b)`.
* Remove needless lifetimes from `get_bucket`.
* Remove unnecessary qualified paths.
* Fix some typos.

Fix some miscellaneous things

---

src/handler/mod.rs
src/socket/mod.rs

I think this is equivalent and a bit cleaner

cleanup socket creation wrt ip mode

---

src/kbucket.rs
src/service.rs

Reduces some unnecessary clones in around the predicate related types

Reduce some clones in predicate impls

---

examples/custom_executor.rs
examples/request_enr.rs
examples/simple_server.rs
src/config.rs
src/discv5.rs
src/discv5/test.rs
src/error.rs
src/handler/crypto/mod.rs
src/handler/mod.rs
src/kbucket.rs
src/kbucket/bucket.rs
src/packet/mod.rs
src/rpc.rs
src/service/test.rs
src/socket/filter/cache.rs

ran:
```
cargo +nightly clippy --fix --all-features -Z unstable-options
```
and `Box::default` manual fixes

chore(clippy): make clippy happy

---

src/kbucket/bucket.rs
src/kbucket/entry.rs

Add `PresentEntry::value_mut` function so the value can be updated

feat: add value_mut function

---

Cargo.toml
examples/custom_executor.rs
examples/find_nodes.rs
examples/simple_server.rs
src/config.rs
src/discv5.rs
src/discv5/test.rs
src/handler/crypto/mod.rs
src/handler/mod.rs
src/handler/session.rs
src/handler/tests.rs
src/kbucket/key.rs
src/lib.rs
src/packet/mod.rs
src/service.rs
src/service/test.rs
src/socket/mod.rs
src/socket/recv.rs
src/socket/send.rs

Allow configuring the protocol id and version at compile time. Reverts #158

Custom protocol id

---

Cargo.toml

Bump to version 0.2.1

---

Cargo.toml

This simply updates the delay_map dependency

Update delay map dependency

---

src/ipmode.rs

Format docs url in rustdoc style

---

README.md
src/lib.rs
src/rpc.rs
src/service.rs

Remove topics in alignment with version 5.2 specs.

Remove topics

---

.github/workflows/build.yml

Update github CI to latest version

---

src/service.rs

Correct comment to correctly describe code.

Correct comment

---

examples/find_nodes.rs
src/socket/mod.rs

Adds some helping functions that make creating a ListenConfig a little bit nicer.

Add some convenience functions for ListenConfig

---

Cargo.toml

This bumps the version to 0.3.0.

Version bump to v0.3.0

---

src/discv5.rs

Removes a pesky ``mut`` I left in :laughing:

Remove unneeded mut from send_ping(..)

---

src/service/test.rs

Use zero ports in tests

---

src/handler/mod.rs

This PR is based on the discv5.2 branch. This fixes an unexpected Handler shutdown during a hole-punching-related event.
N/A

discv5.2: fix unexpected Handler shutdown

---

Cargo.toml

We switched to rlp-alloy, so making this a minor release.

Version bump to v0.5.0

---

Cargo.toml
src/discv5/test.rs

Updates to target the latest ENR version.

Pin to latest ENR

---

Cargo.toml

Version 0.8

---

Cargo.toml

Version bump to v0.10

---

Cargo.toml

Version bump to v0.10.2
